### ISSUE TITLE
How to create a volume that fills a mesh?

### ISSUE THREAD

**Issue by TomClabault** [Zydak/Vulkan-Path-Tracer#7]
I'd like to reproduce subsurface scattering with that.  Like in this render you have on the readme:

![DragonHead](https://github.com/user-attachments/assets/b3bb30fd-092f-4abc-a2eb-b8565f69ea67)

**Comment by Zydak** [comment]
![image](https://github.com/user-attachments/assets/375b9f6c-56da-4a4e-b885-933c5f8c8434)

I believe these were the settings that I used, fully transparent object with really dense medium inside it. I also increased both lights `Emissive Strength` to 10.0. Also note that it will get quite laggy because of the scattering inside the medium so you should lower `Sampler Per Frame` in `Path Tracing Settings` tab
