### ISSUE TITLE
Camera accumulates rolls (rotation around the forward axis) after moving the mouse around for a while

### ISSUE THREAD

**Issue by TomClabault** [Zydak/Vulkan-Path-Tracer#8]
Just drag your mouse with left click and move it in a circle, many many times.

The camera ends up accumulating rotation around the forward axis.

This may be an issue with the order of operation when applying the quaternion rotations.

**Comment by Zydak** [comment]
That's how it's supposed to work. I guess it's a little bit counterintuitive, but I just wanted a camera that moves in relation to its own forward vector. So if you rotate 90° up (x-axis relative to the camera), 90° right (y-axis relative to the camera), and finally 90° down, you end up rotated 90° on the z-axis (roll) relative to the initial rotation. It seems weird, but it makes navigating complex scenes easy since you move relative to yourself not the world, so you can position yourself in pretty much any way you want, for example, upside down, without any problems. It's also pretty standard camera model for a lot flight simulator games, especially those in space where you don't have any point of reference so you move relative to the camera.

**Comment by TomClabault** [comment]
Yeah moving relative to the camera makes sense but I'm not sure you picture the issue I'm seeing.

Here's a video I recorded quickly: https://youtu.be/Y-1TjcK5uyg

Is that intended? I expected the camera to behave like an FPS camera but by simply looking around a scene, you end up upside down even if you don't want to.

I find it hard to control but if that's expected, then I guess it's okay.

**Comment by Zydak** [comment]
If you find yourself accidentally rotated upside down, you can adjust the camera roll using Q and E to get back to the initial position.
