### ISSUE TITLE
"Blocky" renders?

### ISSUE THREAD

**Issue by TomClabault** [Zydak/Vulkan-Path-Tracer#9]
Any idea what may cause the render to be blocky like that? You can see some weird aliasing around the edges and it's pretty pronounced

![image](https://github.com/user-attachments/assets/8696ca91-c8fd-49c3-b115-14823ff02ba5)

I used [this scene](https://github.com/TomClabault/HIPRT-Path-Tracer/tree/main/data/GLTFs) (the-white-room-low..gltf) and basically just navigated the camera inside the room.

I'm on the latest commit of `main`.

**Comment by Zydak** [comment]
Can't seem to reproduce that. Does it happen for every scene or just this specific model?
![Render20](https://github.com/user-attachments/assets/6617ce6b-d5c0-43f8-af1e-22b074b2db14)

**Comment by TomClabault** [comment]
teapot-marble.gltf also show the issue

![image](https://github.com/user-attachments/assets/25507042-18f9-46fc-9e2d-bce29b91c8c8)

Maybe an issue with textures?

**Comment by Zydak** [comment]
I assume there aren't any error messages in the console? Also is it pixelated when switched to Rasterizer Viewport?

![Untitled](https://github.com/user-attachments/assets/9e6edd4c-c99f-4063-bccf-dc353d1b5aa7)

**Comment by Zydak** [comment]
Hmm, it looks like the textures are just getting rounded down in screen space, but the geometry remains untouched. However, since the texture index of the mesh is bound to the geometry, that makes no sense. What happens if you increase the resolution to something like 3000x3000 in the `Viewport Settings` tab in the editor?

If it's some weird thread-group memory error, the aliasing should become less visible due to there being more workgroups. If it's geometry-related, it should stay the same. Also, do you happen to remember if this happened to you before? Did you try these scenes two weeks ago when you were reporting the other issues? If it worked back then on commit [6988421](https://github.com/Zydak/Vulkan-Path-Tracer/commit/69884219a752928029aee7017ce386f860826a31), then I must have messed something up in the past two weeks.

**Comment by TomClabault** [comment]
So I just had a parallel discussion with some guys on Discord and turns out someone  had the exact same issue, on Vulkan, on an AMD GPU (so same configuration as me).

This was due to having code that looks something like that for sampling textures:

```
if (hi.material.baseColMapIndex > -1) {
  albedo = texture(..., uv).rgb;
}
```

This seems to be due to AMD GPUs access descriptors from scalar registers being shared between all threads in the whole wavefront. 

So there seems to be the need for `nonuniformEXT` to tell the compiler to generate some extra code to deal with it.

Maybe you can make sense of that.

**Comment by TomClabault** [comment]
> Also, do you happen to remember if this happened to you before?

Yeah I think it did before iirc.

**Comment by Zydak** [comment]
Ye that would make a lot of sense, the closest thing I have to this if statement is this

```
float texTrans = albedoTexture.SampleLevel(surface.GetTexCoords(), 0).a;
if (texTrans < 1)
{
    Roughness = 0;
    Metallic = 0;
    Color.rgb = 1.0f;
    Ior = 1.0001f;
    Transparency = 1.0f;
}
```

Although not sure if that's where the problem is. Would you mind going to `PathTracer\src\shaders\Material.slang` and deleting this snippet (so lines from 96 to 104)? The shaders should recompile automatically on project startup, if that's the issue then everything should work fine.

**Comment by TomClabault** [comment]
That didn't fix it. I think the issue actually comes from line 90:

`Color.rgb *= albedoTexture.SampleLevel(surface.GetTexCoords(), 0).rgb;`

because `albedoTexture` is a uniform here. Without further indication for the compiler, each thread of the wavefront is thus going to sample the same texture but that's obviously incorrect at object edges when the wavefront spans multiple objects with multiple textures: each thread of the wavefront should then sample the texture of the object it overlaps.

I think you should be using `nonuniformEXT` here but I'm not sure how to add that to the shader since this is an extension and the compiler complains of `undefined identifier 'nonuniformEXT '`

**Comment by Zydak** [comment]
Ok nvm then, actually just try pulling the latest commit.

**Comment by TomClabault** [comment]
All good now!

**Comment by Zydak** [comment]
What a weird bug, I wish there was a way to debug things like these locally because I have no access to AMD or Intel GPUs. These small gpu architecture differences make it a huge pain in the ass to make it work on all hardware. Anyway thanks a lot for reporting it!

**Comment by tigrazone** [comment]
https://github.com/user-attachments/assets/ac1a4574-8d0b-41e8-a607-0613cbbe7509
